### ISSUE TITLE
`cargo-crev`: Prepare and maintain a default list of known crate owners

### ISSUE THREAD

**Issue by dpc** [crev-dev/cargo-crev#100]
I've added `cargo crev edit known` command which allows users to edit their own list of crates.io users (crate owners) that are reputable and somewhat trusted. This information is used when displaying dependencies verification with an intention of helping prioritize reviews of crates that are both unreviewed and from unknown authors.

To make this more useful, we should ship with some decent defaults.

**Comment by CAD97** [comment]
A reasonable objective list could be the primary author(s) of crates under the [rust-lang](https://crates.io/teams/github:rust-lang:libs) and [rust-lang-nursery](https://crates.io/teams/github:rust-lang-nursery:libs) banners.

**Comment by dpc** [comment]
Current list Btw https://github.com/dpc/crev/blob/master/cargo-crev/src/known_cargo_owners_defaults.txt

**Comment by dpc** [comment]
I think I've added majority of if listed owners. We should add more on case-by-case basis.

**Comment by dpc** [comment]
@kornelski prepared a nice list of most trusted crates.io users in #141. Should we just use it as is?
