### ISSUE TITLE
Can't commit or pull reviews: UnbornBranch

### ISSUE THREAD

**Issue by kornelski** [crev-dev/cargo-crev#122]
After `cargo crev review foo` I get:

> Error: Could not not automatically commit
  caused by: reference 'refs/heads/master' not found; class=Reference (4); code=UnbornBranch (-9)

There are two problems here:

1. There is a not-completely-initialized repo somewhere. It may be my fault, as I've tried earlier version of cargo-crev and didn't fully follow instructions.

2. The error doesn't show path to the repo, so I don't know where it is, and I can't fix it.

**Comment by dpc** [comment]
@kornelski Somewhere in ~/.config/crev/proofs you have a git repo coresponding to your URL (the hash of it, so it's not easy to tell which one). I guess we should handle it correctly, though it's a state that shouldn't normally be introduced.

Can you investigate that repo and tell me what exactly is off about it? Is the `master` branch missing?

**Comment by kornelski** [comment]
~/.config/crev doesn't exist on my machine (macOS 10.14, rust nightly).

I did not expect that, because `cargo crev review …` asks me for a passphrase when I start a review, so it has to store that passphrase somewhere, right?

**Comment by dpc** [comment]
> so it has to store that passphrase somewhere, right?

It stores what you edit in a temporary dir, and only after you edit it, it gets signed and stored into the repo. (unless `--no-store` is used).

**Comment by kornelski** [comment]
Yup, got `proofs/$hash/` with:

## No commits yet on master...origin/master [gone]
A  Cp62JH-iG2VWsrPVHauh-zKH-S1lv9WJmPd_m7KFjUI/reviews/2019-01-packages.proof.crev
A  README_USING_THIS_REPO.md

**Comment by kornelski** [comment]
```
$ git remote -vv
origin	git@github.com:kornelski/crev-proofs.git (fetch)
origin	git@github.com:kornelski/crev-proofs.git (push)
```

**Comment by kornelski** [comment]
`git commit` in the dir fixed it.

**Comment by dpc** [comment]
I looked more into it, and I'm not sure if this is worth handling. I mean - this repo did not have `HEAD` set so technically was in invalid state. I don't think it's worth complicating things, just to try to recover from states that should not be there in the first place.

**Comment by MaulingMonkey** [comment]
The most likely way to hit this is when skimming the instructions at:  https://github.com/dpc/crev/blob/master/cargo-crev/src/doc/getting_started.md#creating-a-crevid and overlooking:

> Note: cargo-crev requires the master branch to already exist, so the repository you have created has to contains at least one existing commit.

Github is happy to create an uninitalized/commitless repository through https://github.com/new if you don't select any of these options (and why would you?):
* [ ] Initialize this repository with a README
* [ ] Add .gitignore
* [ ] Add a license

Then, since `cargo crev new id` doesn't appear to do sanity checking to catch this, you end up in this state when you try to start using `cargo crev trust`.  Manually creating a commit, deleting `%APPDATA%\crev`, and rerunning `cargo crev new id` fixes the issue.

**Comment by dpc** [comment]
https://github.com/dpc/crev/blob/a4faa0c10e68ef0bf34206279e00261133676d16/crev-lib/src/local.rs#L436 - probably here there should be a check if the master branch exist, and if not - we should create it.

**Comment by kornelski** [comment]
BTW, instead of instructing users to create a new repo from scratch, you could suggest using forking a template, such as:

https://github.com/dpc/crev-proofs/fork

(of course maybe not this particular url).

The fork UI gives a properly-named, initialized repo, in 1 click.

**Comment by dpc** [comment]
@kornelski That seems like a great idea!

I could create a new account (`crev-templates` or something) with an empty `crev-proof`s repo.

We should still make the code more robust though. :)

**Comment by kornelski** [comment]
Time for Crev github org?

**Comment by dpc** [comment]
Taken :( https://github.com/crev . He doesn't seem to use it anymore, and I asked politely if he would ever release it, but never got a response. Alternative names? I don't want to make it `*-rs` :)

**Comment by dpc** [comment]
https://github.com/crev-dev + https://i.imgur.com/XTyuZlb.png ?

**Comment by dpc** [comment]
I moved to github organization, created a template repo and updated documentation to use one-click forking. Additional benefit - you can can get a list of forks.
