### ISSUE TITLE
Most trusted authors based on crates.io graph

### ISSUE THREAD

**Issue by kornelski** [crev-dev/cargo-crev#141]
Related to #77, I've developed PageRank-like algorithm https://gitlab.com/crates.rs/ranking/blob/master/src/authorrank.rs

Based on PageRank-like implied trust in crate dependencies, and implied trust from crate co-ownership, I've computed this list of possibly most trusted crates.io authors:

dtolnay: 0.44056821847941025
alexcrichton: 0.2734857371556931
dhardy: 0.19951194874024988
kwantam: 0.08550468425169667
burntsushi: 0.08476817568841943
retep998: 0.06850531518290472
erickt: 0.05493393998744088
huonw: 0.034748999490224475
cuviper: 0.027277462074478356
kimundi: 0.026786578276306587
mvdnes: 0.024327111725864707
sfackler: 0.020860867071954087
carllerche: 0.017815639497874666
bluss: 0.017332395969646204
seanmonstar: 0.015721140302683963
byron: 0.015287503933410539
simonsapin: 0.012205481548625092
withoutboats: 0.009779136744287776
nikomatsakis: 0.008857265704182988
newpavlov: 0.008742583419288264
reem: 0.007527253109734015
bvssvni: 0.007388774199513059
lifthrasiir: 0.006780737538469315
japaric: 0.00665847153254592
pitdicker: 0.006637508507409665
aaronepower: 0.006341035141300898
hauleth: 0.006175479755025536
tyoverby: 0.006173041216622486
matthewkmayer: 0.005956424808300577
sergiobenitez: 0.005880582362954293
stebalien: 0.00577562266279871
kbknapp: 0.0057261706496729665
gnzlbg: 0.005541780785014735
tailhook: 0.005463752822917065
amanieu: 0.0054209811473397125
fitzgen: 0.005201566750332928
cramertj: 0.00518314383323331
stjepang: 0.004743796905423105
tomaka: 0.004567049551990742
ivanukhov: 0.00454557066095475
steveklabnik: 0.004219467818880863
vks: 0.003922204067594085
jackpot51: 0.003701261877761638
matthiasbeyer: 0.0036887096691348795
softprops: 0.0032865031360542188
ctz: 0.00323811158036194
brendanzab: 0.003116028177074993
mitsuhiko: 0.003043622181569424
guillaumegomez: 0.0030421743080955095
gankro: 0.00272935638901304
strake: 0.0025501088183357903
dpc: 0.002541846659031492
laumann: 0.0024861044929519517
geal: 0.0024587466214155635
kvark: 0.0023779445014863922
briansmith: 0.002216545713285938
sile: 0.0022070754398942098
frewsxcv: 0.002162059216415564
ogham: 0.002143741805799686
siegelord: 0.002082591508971007
sebcrozet: 0.002050590876568828
oli-obk: 0.0019827990779136325
rust-embedded: 0.001963230577325275
gkoz: 0.001915819466393904
danburkert: 0.0018722652657088335
stepancheg: 0.0018118847756416756
mystor: 0.0018032666189542223
dguo: 0.0017518185797992178
behnam: 0.0017467753634463814
kornelski: 0.0017079797318041326
ssheldon: 0.001653057576344242
debris: 0.0016063084097710917
magiclen: 0.001592867937081985
ticki: 0.0015546164521612657
kodraus: 0.0015544842475796066
manishearth: 0.0015429449741230416
udoprog: 0.0015289756540347317
nwin: 0.0014644831647759944
mgeisler: 0.0014502622137078816
mitchmindtree: 0.0013971399127902591
sdroege: 0.0013943516300991049
danielkeep: 0.0012963082057025526
sunfishcode: 0.0012302579913535052
netvl: 0.0012066570956227643
nical: 0.00118956964672956
yamakaky: 0.00118066300833944
marshallpierce: 0.0011531987125188135
texitoi: 0.0010997890213336763
marwes: 0.001083663133268014
utkarshkukreti: 0.001065904733361798
nathanfaucett: 0.0010323854483798003
emilio: 0.001019392729920658
sgrif: 0.0009896425442344062
jedisct1: 0.0009874041001420434
mcarton: 0.0009692832248579929
koute: 0.0009668615857243053
antoyo: 0.0009649259543583527
llogiq: 0.0009629791539774482
brson: 0.000955204043865685
bheisler: 0.0009480011829504381

**Comment by dpc** [comment]
The related issue is #100 . Let's move the discussion there? :)

**Comment by kornelski** [comment]
I've combined that with crate data:

https://docs.google.com/spreadsheets/d/e/2PACX-1vTjFFezeIQOrJV6BOx2YPnc1osyNaHNnZ_wrYTf8uRVeqN-EsWSgNZZtz1gWXWtOoHg93g7Q5A_b3dd/pubhtml

https://docs.google.com/spreadsheets/d/1JaPJ6PTX-Xi7QpGq3cE3YSCv4sC7uJAAzyj8tMzwc-s/edit?usp=sharing

If you come up a formula that combines crate popularity vs author trust, you can find crates that need reviewing the most.

**Comment by dpc** [comment]
It's kind of implemented as `cargo crev repo edit known`.
