### ISSUE TITLE
`cargo crev change passphrase`

### ISSUE THREAD

**Issue by dpc** [crev-dev/cargo-crev#152]
Especially in the light of #151 , it would be great if people could just re-generate the whole Id file.

**Comment by zicklag** [comment]
This *might* ( no promises ) be something I could find time for. Could you assign this to me to help me not to forget?

Also if you have any quick pointers on what needs to happen that would be cool, to. :slightly_smiling_face:

**Comment by dpc** [comment]
Awesome.

Every id belonging to the user (`OwnId`) is stored "locked" on disk, with its [secret key encrypted (sealed) with user provieded passphrase](https://github.com/crev-dev/cargo-crev/blob/f7efd95ddcd9cf162ef3fa13f094d62e07562fe3/crev-lib/src/id.rs#L41).

Changing a passphrase should be as simple as [unlocking it](https://github.com/crev-dev/cargo-crev/blob/f7efd95ddcd9cf162ef3fa13f094d62e07562fe3/crev-lib/src/id.rs#L137), asking for a new passphrase, and [locking it again, just like when it was created](https://github.com/crev-dev/cargo-crev/blob/f7efd95ddcd9cf162ef3fa13f094d62e07562fe3/crev-lib/src/id.rs#L65).

**Comment by zicklag** [comment]
Oh, sweet. That sounds like a piece of :cake: then. :smiley:

**Comment by dpc** [comment]
BTW. [Saving the file](https://github.com/crev-dev/cargo-crev/blob/f7efd95ddcd9cf162ef3fa13f094d62e07562fe3/crev-lib/src/id.rs#L115) should use safe overwritting: write tmpfile, flush, sync, rename, sync, to make it impossible to corrupt the file on crash. There's [even a common function for that](https://github.com/crev-dev/cargo-crev/blob/f7efd95ddcd9cf162ef3fa13f094d62e07562fe3/crev-common/src/lib.rs#L333) but since we never before overwrote it, I never got to change it to use it.

And yeah, this :crossed_fingers: shouldn't be too much work.

**Comment by kornelski** [comment]
Done in 464fe804b9dced1387696a1a1566303d76454586
