### ISSUE TITLE
Prepare dependencies for recursive metrics.

### ISSUE THREAD

**Issue by dpc** [crev-dev/cargo-crev#208]
We want several recursive metrics/scores: license, Total lines of codes including all deps (recurisvely), total distinct owners/maintainers.

The first step should be to refactor the code to iterate through dependencies in an depth-first fashion, to allow this to happen.

**Comment by Dylan-DPC** [comment]
Send pr :p

**Comment by dpc** [comment]
I think this is somewhat implemented already. Closing for now.
