### ISSUE TITLE
Track unmaintained crates.

### ISSUE THREAD

**Issue by dpc** [crev-dev/cargo-crev#233]
Shamelessly copying what `RustSec` is doing, can't hurt. https://github.com/RustSec/advisory-db/issues/134

The question is - can we reuse existing issues system for that, with some convention, or do we need any additional primitives?

**Comment by dpc** [comment]
Maybe we can just make the `version` field optional. Without version the review would be for the whole package. There the reviewer can just put any cries or praises for the package as a whole, not just particular version. Some additional keys might be useful to mark common problems: lack of maintainers, obsoleted, etc.

**Comment by BurntSushi** [comment]
I like the idea of reviews for whole packages. My only concern there is that praises (or criticisms) may become stale. I guess the timestamp would help alleviate that.

**Comment by dpc** [comment]
Timestamp is in all proofs by default, so we can tweak how it works once it become a problem, yes.
