### ISSUE TITLE
Read passphrase from pass

### ISSUE THREAD

**Issue by kpcyrd** [crev-dev/cargo-crev#234]
I've started publishing [some reviews](https://github.com/kpcyrd/crev-proofs) with crev but I have to paste the password from my password manager every time.

I'd like to specify `pass show my-crev-password` as a command that's executed by crev to get the password on its own.

**Comment by dpc** [comment]
You can set `CREV_PASSPHRASE` environment if you like, or even write a shell script wrapper that would read passphrases from `pass` and lunch a `cargo crev review`.

I think I'm open for ability to configure `crev` to ask for passphrase via any shell command. Probably via another environment variable like `CREV_PASSPHRASE_CMD`?

The code would basically go here https://github.com/crev-dev/cargo-crev/blob/2c9a6cc80c00086324ac879a4c10b61f64bb249f/crev-common/src/lib.rs#L193 and if env is set, would start a command and read the output.

Comments and PRs are welcome. :)

**Comment by MaulingMonkey** [comment]
If you happen to be using KeePass, you can configure auto-type to select the right entry and auto-type it for you with the following settings on Windows for cmd.exe prompts - there may be an equivalent that will work elsewhere:

![image](https://user-images.githubusercontent.com/75894/64067984-7a858c80-cbe6-11e9-8342-1f602c9e5a23.png)

Ctrl+Alt+A when prompted by crev for a password will then ask keepass to autotype it, causing it to prompt to unlock the password database if it's currently locked.

**Comment by kpcyrd** [comment]
`CREV_PASSPHRASE_CMD` is the kind of solution I'm looking for, but I would like to add the command to a config file so I don't need to have this variable set in my environment for everything. :)

**Comment by BurntSushi** [comment]
I don't think `cargo crev` has a config file? If not, I don't think this alone is worth adding one for.

I too would be very happy with `CREV_PASSPHRASE_CMD`.
