### ISSUE TITLE
PR template asks for nightly `cargo fmt`.

### ISSUE THREAD

**Issue by afck** [crev-dev/cargo-crev#236]
The [PR template](https://github.com/crev-dev/cargo-crev/blob/master/.github/PULL_REQUEST_TEMPLATE.md) asks for `cargo +nightly fmt --all`, which currently would want to change a lot of formatting and doesn't seem to be enforced by CI? Also, the outcome of that command depends on the latest installed nightly rustfmt version.

It might be more maintainable to ask for the rustfmt version that is shipped with the same stable Rust release [fixed in the `.travis.yml`](https://github.com/crev-dev/cargo-crev/blob/2c9a6cc80c00086324ac879a4c10b61f64bb249f/.travis.yml#L12), and to check that in CI?

**Comment by afck** [comment]
Also, I noticed that `cargo clippy --all-targets` passes without warnings. :tada: 
That could also be added to CI?
(Looks like both were already there, and were removed in [this commit](https://github.com/crev-dev/cargo-crev/commit/2e906250354d6de32666b466281f26bd04e48435#diff-354f30a63fb0907d4ad57269548329e3) — was that by accident?)

**Comment by dpc** [comment]
Nightly is only for `merge_imports = true`. If someone uses stable, that's fine too. :)

I have found enforcing formatting in CI to be somewhat constraining. If this project becomes really busy with PRs, we can enable it, but before that - I don't really mind.

Same with Clippy . I like to run it periodically and fix all the warning, and not have to worry about it all the time.
