### ISSUE TITLE
"Proof body too long" error on cargo crev fetch

### ISSUE THREAD

**Issue by lo48576** [crev-dev/cargo-crev#246]
# Summary
"Failed processing a proof: Proof body too long" error is reported on `cargo crev fetch all` and `cargo crev fetch trusted`.
cargo-crev command itself exits successfully with exit code 0.

# Expected result
No error happens.

# Actual result
An error is reported.

Output (after removing `~/.local/share/crev`):
```
$ cargo crev fetch trusted
Fetching https://git.sr.ht/~icefox/crev-proofs... OK; 4 new trust proofs; 30 new package reviews
Fetching https://github.com/qnighy/crev-proofs... OK; 2 new trust proofs; 5 new package reviews
Fetching https://github.com/BurntSushi/crev-proofs... OK; 1 new trust proofs; 6 new package reviews
Fetching https://github.com/lo48576/crev-proofs... OK
Fetching https://github.com/dpc/crev-proofs... OK; 13 new trust proofs; 99 new package reviews
Fetching https://github.com/Lokathor/crev-proofs... OK; 4 new trust proofs; 3 new package reviews
Fetching https://github.com/Ralith/crev-proofs... OK; 3 new trust proofs
Fetching https://github.com/Mark-Simulacrum/crev-proofs... OK; 1 new trust proofs; 2 new package reviews
Fetching https://github.com/MaulingMonkey/crev-proofs... Failed processing a proof: Proof body too long
OK; 2 new trust proofs; 56 new package reviews
Fetching https://github.com/oherrala/crev-proofs... OK; 4 new package reviews
Fetching https://gitlab.com/KonradBorowski/crev-proofs... OK; 3 new trust proofs; 21 new package reviews
Fetching https://github.com/kornelski/crev-proofs... OK; 1 new trust proofs; 121 new package reviews
Fetching https://github.com/Canop/crev-proofs... OK; 1 new trust proofs; 6 new package reviews
Fetching https://github.com/kpcyrd/crev-proofs... OK; 2 new trust proofs; 7 new package reviews
$
```

<details>
<summary>Output of second time execution (when `~/.local/share/crev` is present)</summary>
Output (second time):

```
$  cargo crev fetch trusted
Failed processing a proof: Proof body too long
Fetching https://github.com/lo48576/crev-proofs... OK
Fetching https://github.com/Lokathor/crev-proofs... OK
Fetching https://github.com/oherrala/crev-proofs... OK
Fetching https://github.com/Mark-Simulacrum/crev-proofs... OK
Fetching https://github.com/BurntSushi/crev-proofs... OK
Fetching https://github.com/kornelski/crev-proofs... OK
Fetching https://git.sr.ht/~icefox/crev-proofs... OK
Fetching https://github.com/Ralith/crev-proofs... OK
Fetching https://github.com/Canop/crev-proofs... OK
Fetching https://gitlab.com/KonradBorowski/crev-proofs... OK
Fetching https://github.com/qnighy/crev-proofs... OK
Fetching https://github.com/kpcyrd/crev-proofs... OK
Fetching https://github.com/dpc/crev-proofs... OK
Fetching https://github.com/MaulingMonkey/crev-proofs... Failed processing a proof: Proof body too long
OK
$
```
</details>

# Environment

* cargo-crev version: current master (bf33e6b5ac58)
    + I also tried cargo-crev 0.9.0 and same error happened.
* Installation: `git clone` and `cargo install --path .` for master
    + `cargo install cargo-crev` for 0.9.0
* OS: Gentoo Linux (up to date)

**Comment by dpc** [comment]
Ah, it's just @MaulingMonkey decided to backup wikipedia in one of their reviews. https://github.com/MaulingMonkey/crev-proofs/blob/master/6OZqHXqyUAF57grEY7IVMjRljdd9dgDxiNtr1NF1BdY/reviews/2019-09-packages-73Zwaw.proof.crev#L2546 :rofl: (jk - I really appreciate these in depth reviews)


Seems like serde-yaml was happy to  serialize such a long document, but is complaining when deserializing it.

It seems to me that it's reasonable for crev to reject too long documents, but we should fail to create them so that authors are aware that they went a bit too far, and eg. move our some details into separate file or something.

Also, maybe we can somehow raise the limits. The question is - how much is long enough, trading potential attackers exhausting resources vs usability.

**Comment by dpc** [comment]
In this case, it seems to me our limits are just too low. I'd appreciate a PR raising them (if possible). I'll try to fix it myself once I get to it.

**Comment by dpc** [comment]
The good part is - seems that other then the error message and ignoring this particular proof, crev is still working OK.

**Comment by icefoxen** [comment]
Whatever limit we decide on, it might be wise to note it in the review template comments, since it has so much other good info on what to expect for a review.

**Comment by dpc** [comment]
@icefoxen We should make sure that serialized proof can be deserialized. Right now we don't, and also the length limit is in a different place of code and is not tight to the deserialization, which is not great. Should be simple refactor, with introducing an explicit `deserialize_proof`-like function to use everywhere, and testing if it passes every time user saves the proof draft.

PRs welcome. I'll get there at some point too. Lets keep this issue open until structurally addressed.

**Comment by MaulingMonkey** [comment]
> Would be nice if serde had a way to put a global lenght limit somewhere via proc macros

A std::io::Write wrapper could impose a length limit.  Would *probably* work?

**Comment by dpc** [comment]
@MaulingMonkey Yes, but that still requires the code trying to deserialize to do something extra. My intention was that the normal, most obvious way someone would deserialize `PackageReviewProof` type, would enforce the lenght limit because of some `#[serde(lenght_limit = "1024KB")]` kind of thing.
