### ISSUE TITLE
Doc issue: getting started should not point to glossary

### ISSUE THREAD

**Issue by HadrienG2** [crev-dev/cargo-crev#251]
Currently, the "getting started" section of the docs (or at least the version available on docs.rs) contains a copy of the "glossary" section. This should probably change.

**Comment by dpc** [comment]
How did that happen...

**Comment by dpc** [comment]
Now I get it. I've added some spacing to help myself in the future.

**Comment by dpc** [comment]
https://docs.rs/cargo-crev/0.10.1/cargo_crev/doc/user/getting_started/index.html
