### ISSUE TITLE
Help to develop etiquete in regards to critical review feedback.

### ISSUE THREAD

**Issue by dpc** [crev-dev/cargo-crev#258]
Getting critical feedback about your code from random strangers from the Internet will naturally not always go well with emotions and egos of parties involved. Sometimes, the reviewer will be wrong about their judgment making them look unfair etc.

It would be good to establish an etiquette and set of standards, to make everyone involved feel more comfortable.

**Comment by dpc** [comment]
* Judge the code, not people
* Remember that one of the main goals is to improve the ecosystem
* If possible, report the feedback upstream so the issues can be addressed
* If possible, prioritize re-reviewing newer versions of crates that addressed reported issue

**Comment by DestyNova** [comment]
> Judge the code, not the people

Although this is probably already the goal during reviews, it's natural for people to feel like maybe they are being judged when all of the comments are negative, or e.g. when the conclusion is like "overall I'd give this a entire effort a big thumbs down".
Perhaps it would be good to at least start and finish with some friendly comments that help make the intentions clear. Then maybe at the end, a summary of some of the main pros/cons observed.

Another thing, I've seen one or two reviews where the author answers some of the feedback, or even implements fixes. I think it's important to thank and encourage them for this.

**Comment by mleonhard** [comment]
Start out the review by stating the requirements of the reviewed code.  This builds rapport with the stranger who is receiving your review.  Relate all feedback to the code's requirements.

Bug reports are easy to accept.  To report a bug, suggest a new test case that exercises the bug.  Explain a potential fix if you want.

Design critique can be hard to accept.  See if you can change your design critique into a bug report by suggesting a new test that demonstrates the shortcoming.

If the design problem is not testable, then you need to explain why the code will better meet the requirements after the change.
Start out by stating which of the requirements you think the code currently meets.  Then explain how the code will better meet specific requirements with specific changes.  Watch out for comments on things that are not in the requirements.  A comment like "users will will expect functionX to do Y but it doesn't and they will be confused" may not be received well if the requirements don't include "easy to use".  Other requirements that are often missing are "easy to learn", "easy to maintain", and "modular".  Avoid commenting on things that are not in the requirements but you think should be.  Instead, first suggest adding them to the requirements.

Teaching is an important part of code reviews.  When you suggest a change, try to link to background material so the code author can learn more.
- https://rust-lang.github.io/api-guidelines/
- https://doc.rust-lang.org/1.47.0/book/
- https://doc.rust-lang.org/rust-by-example/
