### ISSUE TITLE
`cargo crev crate verify` hangs for a long time (15+ seconds) when processing the local crate.

### ISSUE THREAD

**Issue by Lokathor** [crev-dev/cargo-crev#269]
Is this expected? The Getting Started Guide doesn't mention that I should expect that. I tried two different projects and they both quickly showed all the crates.io dependencies and then seemed to freeze for quite a while before printing the local crate's line at the end.

Also, and this could be related, when `ogl33` was a local crate it was reported as having 94,107 lines and 3,783 geiger hits. When it was used as a dependency in the second project i tried it was reported as 19,172 lines and 757 geiger hits.

Is it over calculating the local crate in some way that's super computationally intensive? That should probably be documented in the Getting Started guide if so.

(Version 0.13.0)

**Comment by dpc** [comment]
I think it is taking a long while to calculate the digest of the local crate. Maybe you have a lot of additional data that it has to go though. I should probably disable calculating digest for local crates at all.

**Comment by dpc** [comment]
I pushed a fix to master branch. I hope it will help. geiger and tokei will still do its job. 

I'm not sure about the geiger count. Maybe there's something inside your local source code (or `./target` that confuses geiger?

**Comment by dpc** [comment]
I think this is fixed.
