### ISSUE TITLE
Request: Some way to ignore a review of a crate if it's by the author of that crate.

### ISSUE THREAD

**Issue by Lokathor** [crev-dev/cargo-crev#276]
Basically the author of a work is often blind to the problems of a work. If there's a bug that they put in there on accident, they're obviously not going to see it during review because they'd fix it if they did see it.

I know that the identities aren't currently linked to anything so there's no _for sure_ way to determine if the ID of a review is connected to the person who wrote the crate being reviewed, but even a best effort system (such as looking at the git URL of the ID and looking at the authors, repository, and homepage entries in the crate's Cargo.toml file) would probably be helpful here.

**Comment by dpc** [comment]
Since there's no reliable way to do it, it's better to embrace it than try to fight it. A review of the author is better than no review at all since it at least certified that the author knows about this release, and the content digest is the same as the author expected.

Eventually there would be more and more reviews so reviews and the author is not any more reputable than you or your WoT is willing to make them.

**Comment by chrysn** [comment]
Would be opt-in flagging the review yourself make sense, like in `understanding: author` (or `coauthor`)? Not sure if that fits precisely in "understanding", could just as well be a separate field that indicates whether the reviewer has not contributed code, contributed some code or contributed a major portion of the code.

I think that it'd make sense to have self-reviews published, but currently don't publish reviews on my own crates as the review might appear disingenuous. The possibility to indicate that would remove that impediment to writing reviews, and considering the points you made would not require any immediate changes in the reported trust.

**Comment by dpc** [comment]
@chrysn 

Right now I'm of the opinion that this is not a problem at all, for many reasons. And potential "solutions" introduce more problems than their "solve".

At least until something is decided to change, I would not hold on reviewing own crates. It's not disingenuous. The official party line is that it is encouraged. If anyone trusts you as a reviewer of other's people code, they trust you to do a decent job writing/reviewing your own code as well. Eventually, people should be using `verify --redundancy N` anyway, and biases of the authors are going to disappear in the wisdom of the crowd.
