### ISSUE TITLE
Verify doesn't show trusted owners any more

### ISSUE THREAD

**Issue by kornelski** [crev-dev/cargo-crev#280]
`cargo crev verify` used to have a column that shows number of trusted owners and number of reviews available for a crate. I used that information to prioritize which crates I'm going to review next (i.e. pick rows with all 0s). 

If feels like only 1% of my deps are marked as "pass", so I the amount of reviews I need to do is larger than I can manage. I want to first review packages that seem to be the highest risk. Without that extra information the full list is just too overwhelming and depressing.

**Comment by dpc** [comment]
`verify` output was getting really long, so on `master` there are now `--show-xyz` arguments, and `--show-all` if you just want everything.

I like to do `--skip-verified --show-leftpad-index` and `| sort -k6 --numeric-sort`  or something like that - depending on what I'm doing.
