### ISSUE TITLE
Verify doesn't show what the issues are

### ISSUE THREAD

**Issue by kornelski** [crev-dev/cargo-crev#281]
`cargo crev verify` shows red `1` for some of the dependencies in the "issues" column, but it doesn't display any information about the issue.

`cargo crev crate info` doesn't show the issues, and `cargo crev --help` is unhelpful (searching the whole tree of subcommands is painful), so I'm lost.

**Comment by dpc** [comment]
`cargo crev repo query issue ...`, but yeah... 

Issues itself wouldn't really fit in columnar view of `verify`. Maybe at least we could print a `stderr` message. "some issues detected, use `cargo crev repo query issue <crate_name>` if there were any issues.

**Comment by dpc** [comment]
Added a message. #263 already lists displaying issues in `crate info`.
