### ISSUE TITLE
crate version can't be specified with --vers

### ISSUE THREAD

**Issue by kornelski** [crev-dev/cargo-crev#282]
Cargo uses `--vers x.y.z` to specify crate versions for commands. `cargo crev` uses `name [version]` pattern instead, which wasn't obvious to me. I've also tried `name@version` (pattern used by npm), but it showed a generic error message about crate not being found, without indicating that it's a wrong syntax.

I suggest supporting `--vers` and/or providing advice in case there's `@` in the crate name.

**Comment by dpc** [comment]
I kind of like the `[ crate_name [ crate_version ]]` positional pattern, though if `cargo` is doing something different then it's a strong argument to support it. Maybe we could support both, or at least implement helpful messages, yes.
