### ISSUE TITLE
First-Time UX Confusing

### ISSUE THREAD

**Issue by ralfbiedert** [crev-dev/cargo-crev#283]
Hi,

After today's Reddit posts regarding the (repeated...) treatment of UB in upstream  dependencies I thought to give `crev` a shot and review the dependencies of our project. Unfortunately I didn't get very far before I was too frustrated and gave up. I took a few minutes to write down my user journey, maybe you find this interesting:

- I started out by landing in some random repo that was a clone of `crev-proofs` and didn't quite understand where to start. 
- I had to click few times to find the actual "crev" repo, which was not `crev` but `cargo-crev` (why doesn't the `crev-proofs` README template explain that in 1-2 sentences and link to "crev proper" prominently?) and then click the "Getting Started" link hidden in the middle of that page.
- Getting the tool I wanted pre-compiled binaries, on MacOS using `brew` in particular (too lazy to manually download and copy a binary). However, self compiling worked alright (`cargo install cargo-crev`). So, how _do_ I start?
- `cargo crev` only printed a general help but didn't lead me to getting a "successful" first-time user output (why not print `Run 'cargo crev ...' to review this crate` somewhere?). 
- Maybe `cargo crev crate review` ... Something something "Crate name argument"? Huh? Oh, maybe wrong command. Time to check README.
- Ah, `cargo crev crate verify` ... alright. It's doing something. Wait, the output looks nothing like advertised on web page. No geiger, no issues, just weird flags:

```
status issues flgs crate                version         latest_t       
none    0   0 ____ constant_time_eq     0.1.4           
none    0   0 ____ fallible-streaming-iterator 0.1.9           
none    0   0 ____ pkg-config           0.3.17          
none    0   0 ____ rustc-demangle       0.1.16          
```

- It says "use one or more `--show-xyz` options to print more details." ... Uhm, which one? Is Geiger an option now since the README was written? Trying `cargo crev crate verify --help` suggested `--show-geiger`. Oookay, let's try that:
- `cargo crev crate verify --show-geiger` ... `error: The argument '--show-geiger <show_geiger>' requires a value but none was supplied`
- Ah fuck it, I'm too busy anyway, maybe another time.

Happened with `cargo-crev 0.15.0` on macOS 10.15.2. As mentioned in the beginning, this is not really an issue, more of a report I wanted to share. Feel free to close.

**Comment by dpc** [comment]
Hi. Thank you for letting me know, I really appreciate it!

The Getting started guide can be found here: https://docs.rs/cargo-crev/0.15.0/cargo_crev/doc/user/getting_started/index.html and I do link to it from https://github.com/crev-dev/cargo-crev . If you happen to try it, please let me know how it went.

Unfortunately `crev` does require a bit of initial understanding, and I doubt we can ever make as simple as "plug and play" without having to read a bit how to start. Though we can try to get closer to it, I'm sure.

I'll need more time to process all your points, and see if there are ways to improve the experience.

There has been a relevant ticket opened at #284 , BTW.

**Comment by dpc** [comment]
`v0.15.1` fixes  the `error: The argument '--show-geiger <show_geiger>' requires a value but none was supplied` error. Thanks a lot of catching it!

**Comment by ralfbiedert** [comment]
Thanks for the links! Two clarification for my original report:

- When I followed the Reddit post it brought me to your proofs repo (https://github.com/dpc/crev-proofs), in that top level README (maybe in the [master template](https://github.com/crev-dev/crev-proofs)) it would have been nice to link to the link you posted as well, for example:

> Proof Repository
>
> This git repository is used a Crev Proof Repository.
>
> You can find more about [Crev and how to get started here](https://github.com/crev-dev/cargo-crev/blob/master/cargo-crev/src/doc/getting_started.md).

- In retrospect, that `cargo crev crate verify` only printed a fraction of what was shown in the examples with no clear (at least to me) path how to get more was biggest factor in saying "maybe later".

**Comment by dpc** [comment]
> only printed a fraction of what was shown in the examples with no clear (at least to me) path how to get more was biggest factor in saying "maybe later".

In the latest release I decided to make some columns optional, because the output was getting to long. That's why I've added this `-show-xyz` message. I'll improve it a bit.

**Comment by dpc** [comment]
@ralfbiedert See if it makes more sense now.

**Comment by dpc** [comment]
I've updated the https://github.com/crev-dev/cargo-crev/wiki/Proof-Repository which default Proof Repository README.md links to.

**Comment by jhpratt** [comment]
FWIW I'm just using crev for the first time, and have had pretty much the same experience. What's documented is _nothing_ like what is visible, and I can't find an explanation of what "flags" are, even after searching.

**Comment by dpc** [comment]
@jhpratt Thanks for feedback. Use `--help` on the command to get `flags` documentation.
