### ISSUE TITLE
Usability issues with the command-line interface

### ISSUE THREAD

**Issue by kornelski** [crev-dev/cargo-crev#284]
To me the "noun verb" grouping of commands is unhelpful. On a first glance it seems like a logical thing to do, but it has many problems in practice:

* for many operations there's actually more than one thing involved, so it's unclear *which* noun is the special one. For example if an operation requires *querying repositories about crate information* it's entirely arbitrary whether that's `crate info` or `repo query`. 

* I can't develop intuition when to use `cargo crev crate`, because it changes the meaning of "crate" depending on subcommand. Sometimes it's the current crate, sometimes it's some other crate, sometimes it's search for crates. This seems wrong to me, because `crate verify` verifies my crate in the current directory, and given that I'd expect other `crate` subcommands to be consistent and also apply to my crate in the current directory, but they don't.

* the choice of top-level nouns is odd. For example, reviews are an essential object for crev, but they weren't given a noun in the UI. There's no `cargo crev review create`. Instead of `review delete` there's `crate unreview`.

* To me repositories are an implementation detail, more like a transport mechanism. So to me `cargo crev repo` is as weird as `cargo crev http` would be. Because most crev features are backed by some repo somewhere, the `cargo crev repo` subcommands perform lots of unrelated operations, from editing my readme to searching other people's reviews.

* The commands are long to type. I've noticed you use an undocumented `c v` shortcut! Poor users who read `cargo crev --help` end up suffering the long versions.

* There is no similarity between verbs. The verbs don't apply equally to the nouns. A "noun verb" design would make sense for a music player that allows `song play` and `album play`, but crev's nouns aren't interchangeable like that. In crev's case these are mostly just unique two-word commands.

* structopt/clap doesn't think of them as nouns and verbs, but as nested subcommands. Because of that it doesn't display full commands, and `cargo crev --help` is useless.

Look at `cargo` itself. It has `cargo update`, not `cargo index update`. It has `cargo build`, not `cargo crate build`. `cargo publish`, not `cargo package publish`. Flattening of options allows `cargo --help` to display the most common and most useful options.

**Comment by Lokathor** [comment]
very flat, always the verb first, would probably be good

**Comment by dpc** [comment]
@kornelski Wasn't it you complaining a while ago that there are too many top level commands? I can't find it now (maybe it was on riot), but I swear - someone wanted less top level commands because otherwise the output of initial `--help` was too long and it is hard to find what's you're looking for. I thought it was you since I at very least remember: https://github.com/crev-dev/cargo-crev/pull/219 . It's not very important who anyway.

I appreciate the feedback, and I'm open for room to tweak things, but I am skeptical there is a way to make everyone happy. A tool that can do many, many things will have a lot of commands, switches and they all have to sit somewhere. No way around it until we have general purpose AI and good voice control.

I need more time to go through your points and think about it on case by case basis but just a couple of initial points:

* I have implemented `cargo crev config completions` to help with typing.
* I have gave commands one letter aliases for the same reason. I wish it would just show up in `--help`. 
* Writing documentation is mostly counter-productive. There's plenty of docs, and people keep popping on Riot channel and ask about things that are in the docs. The more docs there is, the more diluted they become, and it's harder for people to find what is actually important. Plus it takes forever to keep updating them. And I have unfortunately so little time.

I'll get back to this issue over the weekend. Feel free to discuss more and remind me if I forgot about it.

**Comment by kornelski** [comment]
Yes, I've also complained about too many top-level commands :) Now crev has swung into the other extreme of not having *any* useful top-level commands. 

Both extremes suffer from not having useful `--help` that quickly helps to use the tool.

I agree that out-of-band documentation won't solve it. That's why I'm so picky about quality of `--help`.

Command-line is `crev`'s user interface, so exact details of that interface matter. 

GUI programs can suffer from having too many windows and too many buttons, and CLI programs can suffer from having too many subcommands and switches.

As for more specific actions:

1. Current content of `cargo crev --help` is not very helpful. I'm not sure if structopt can do better than that. Maybe this help text could be replaced by a hand-written one? Or structopt could be replaced by direct use of clap that is more customizable? For example, clap can display commands in custom order, not alphabetical. This allows displaying most common/relevant commands first, and rare ones last (e.g. everyday `verify` before troubleshooting-only `git`)

*

**Comment by dpc** [comment]
@kornelski : All right. I've read all the details. I guess I acknowledge most of the problems mentioned.


@Lokathor 

> very flat, always the verb first, would probably be good

That's what we had first, and it had it's own problems.




I guess the root of the problem is a wrong PoV of the categorization I've used. I should have probably used top-level nouns for the objects that users is creating/manipulating, instead of ... I don't really know what I did so far. I guess things that made sense from the internal point of view.

As per `structopt` - it can do everything that `clap` can, and I think I can fix the minor issues (sorting, comments, short options, etc.) by just digging a bit around.

I guess what I'm going to try to do next is comming up with a new list of top-level nouns. **I invite you to present your own vision too*.

**Comment by kornelski** [comment]
I would like to try a different approach, and design from perspective of workflows. I'm not suggesting literally having some `cargo crev <workflow>`, but to think how it's used, and maybe it'll be clearer how to present it.

- which things all users need to set this up?
- which operations are used by users who just want to review safety of their dependencies?
- which operations are used by contributors who review other people's crates? Does it differ whether they review for security issues, or general bugs and code quality?
- which operations are for debugging, troubleshooting, customizations that aren't day-to-day operations?


Currently `cargo-crev` does everything for everyone at once, and each type of user has to figure out which of the many commands and switches are for their workflow.

**Comment by dpc** [comment]
I have no idea how do people use `cargo-crev`. And even my workflows are still evolving. And changing features will unlock new workflows. And I have very little time to implement it, and even less to think about it. :D

**Comment by Lokathor** [comment]
Here are some basic workflows

When setting up a profile:
* cargo crev "set me up my profile"

When checking your profile:
* cargo crev "who do i directly trust"
* cargo crev "who do i transitively trust"
* cargo crev "let me edit who i trust"
* cargo crev "let me see all the reviews i've written"
* cargo crev "let me edit/delete a review"

When checking out a crate:
* cargo crev "check for updates from my trusted sources"
* cargo crev "tell me about the crate in the current directory folder"
* cargo crev "let me review dependencies of this crate that aren't reviewed yet"
* cargo crev "let me review this crate"
* cargo crev "please save all that work I just did and push it up to git so others can see it"

**Comment by kornelski** [comment]
Can cargo crev commands be divided into "porcelain" and "plumbing"? (i.e. higher-level user interface, vs lower-level interface that's mainly machine-oriented) 

Maybe even the crev command could be split into `cargo crev` for humans and `cargo crev-mess-with-repos` for things that talk YAML. Moving stuff out of sight of regular users would help reduce confusion/overwhelming from too many commands they don't need.

For example I don't know what to do with `cargo crev repo query review`. That doesn't look like something a regular user would use to read crate reviews. This looks more like specialized data dump function for export… somewhere.

**Comment by dpc** [comment]
> Moving stuff out of sight of regular users would help reduce confusion/overwhelming from too many commands they don't need.

Then they going to complain that they can't do some extra stuff that they want, or create issues with a feature request for something that is already implemented. :man_shrugging: 

I''m not convinced by either "workflows" or trying to hide some stuff.

Right now, I think flattening `repo` and rethinking `crate` subcommands is my plan.

**Comment by dpc** [comment]
People don't jump into `git`, `awk`, `vim` or a new programming language an expect to start rolling without a tutorial or some help. Ultimately, I don't expect this to be much different for `cargo-crev`. There's enough of essential complexity and novelty, and not even existing tools that they might know already to make it look more familiar.

If someone wants to roll with some workflow, then they should read some guide. Maybe the existing Getting Started Guide, or some other, more targeted guides.

I also need to find a way (even if manually prepared) to give users the tree of all implemented commands for a reference.

**Comment by dpc** [comment]
`repo` subcommands

```
    dir        keep here
    edit       keep here
    fetch      move to `cargo crev proof fetch`?
    git        keep here
    import     keep here
    publish    move to `cargo crev proof publish`?
    query      move to `cargo crev proof query` or something?
    update     rethink altogether
```

I'm less sure about the `crate`

```
    clean       Clean a crate source code (eg. after review)
    diff        Diff between two versions of a package
    dir         Query source directory of a package
    goto        Start a shell in source directory of a crate under review
    help        Prints this message or the help of the given subcommand(s)
    info        Display rich info about the given crate
    mvp         Most valuable players (reviewers)
    open        Open source code of a crate
    review      Review a crate (code review, security advisory, flag issues)
    search      Search crates on crates.io sorting by review count
    unreview    Untrust (remove) trust
    verify      Verify dependencies
```

I think I need a new top-level noun for `proof` / `review`?


`repo fetch` -> `proof fetch`  or just `fetch`?
`repo publish` -> `proof publish` or just `publish`?
`repo query` -> `proof query`

`crate review` -> `proof create`?


There's a bit of naming issue that `proof` usually, but not always contains the review, issues, advisories.


`proof create` and `review create` could be similiar, but start with different defaults etc.

**Comment by dpc** [comment]
It's also very plausible to have duplicates of stuff  - verbs in top level for most commonly used actions.

**Comment by kornelski** [comment]
Most common verbs at top level would be good kind of crowding :)

The only commands I ever use are:

* `fetch all` (begin session)
* `verify` (decide what to review)
* `open` (start review)
* `review` (end review)
* `publish` (end session)
* and I somehow added other people's proof URLs to crev. I think it was `repo fetch url`, but I don't know if that's the right way to do it. I suspect it's a weird limbo where a URL is fetched, but not trusted, but `cargo crev id trust` wants IDs, not URLs.

So to me if crev had these 6 commands in `--help` and nothing else, it'd cover 100% of my workflow :)

**Comment by dpc** [comment]
They all used to be on top, I think. I'll look for a way to separate them as such in the `--help` to make a clear distinction between formal commands, and "shortcuts".

As per `trust <url>` - it is on my radar and I'd like to have it, but I didn't get to it. PRs welcome.

**Comment by kornelski** [comment]
BTW, `crev id <subcommand>` works fine as a group IMHO. Unlike other commands, ID management is a specific area rather separate from everything else.

**Comment by kornelski** [comment]
`verify` and `review` could be top-level. Verify is what users want. Review is what crev needs :)

**Comment by dpc** [comment]
`review`/`crate review` already does display information about the columns BTW.

**Comment by dpc** [comment]
I want to add/change/move:

* query proofs by authors id
* query proofs by crate [version]
* query issues for a crate [version]

What should the CLI for this be?

**Comment by kornelski** [comment]
It depends what these commands are used for?

Currently `crev repo query issue` dumps YAML. I don't know if that's just unpolished UI, or whether it's meant as a machine-readable export.

If querying is for YAML export, then it could be `crev export proofs --author=id` `crev export proofs --crate=name`

If it's for human-readable display, then `crev show proofs` again with `--author=id` `--crate=name`. The inspiration here is `git log` which takes filtering options.


For issues, I'd try to sum them up in `crev verify`. Maybe you can inject one-liners that ignore columns:

```
status issues flgs crate                version         latest_t
none    0   0 ____ take_mut             0.2.2
none    0   0 ____ matches              0.1.8
none    0   0 ____ sha1                 0.6.0
# sha1: [dpc's review] it's busted, blake3 is the future!
none    0   0 ____ bytecount            0.5.1
none    0   0 ____ winapi-build         0.1.1
```

and there could be `cargo crev show <crate>` that shows all relevant info about the crate, with possibility to narrow it down like `--issues` that displays only issues.

**Comment by dpc** [comment]
So you're saying that filters could be optional arguments? I see.

I don't think one liners are going to work in `verify`. There's just no way to compact them into one-liners, and it's important: who wrote them, when, why, etc. That's why yaml output is used right now. It's semi-human readable.

**Comment by dpc** [comment]
I pushed some initial approximation.

**Comment by kornelski** [comment]
Aliases really helped.
