### ISSUE TITLE
Outdated Cargo.lock in 0.15.1 release

### ISSUE THREAD

**Issue by kpcyrd** [crev-dev/cargo-crev#286]
Hey! The lock file for the 0.15.1 release is outdated and breaks `cargo build --release --locked`.

**Comment by dpc** [comment]
@kpcyrd On the master branch or the release itself?

**Comment by dpc** [comment]
I have replaced the tag with to include the missing `Cargo.lock`

**Comment by dpc** [comment]
`cargo install -f cargo-crev` works. So I guess that's all I can do right now. Thanks for letting me know.

**Comment by kpcyrd** [comment]
The 0.18.3 release has the same problem again unfortunately.

**Comment by kpcyrd** [comment]
0.19.0 works fine, thanks!

**Comment by kpcyrd** [comment]
Happened again with 0.19.3

**Comment by dpc** [comment]
We could use some github actions automation for doing the releases. I know I tend to make all of these mistakes myself, when I am publishing stuff from my local laptop.

If you happen to know of any Rust projects where we could copy & paste stuff like that to automate it and make more reliable, please let us know!
