### ISSUE TITLE
New lockfile format unsupported

### ISSUE THREAD

**Issue by Nemo157** [crev-dev/cargo-crev#288]
Since Rust 1.41 the [default lockfile format has been updated](https://github.com/rust-lang/cargo/pull/7579/). This has been supported since Rust 1.38, but unfortunately `cargo-crev` is still using `cargo v0.38` from Rust 1.37.

Trying to run `cargo crev crate verify` on a repo using the new format gives

```console
> cargo crev crate verify
Error: failed to parse lock file at: /tmp/tmp.9Ks6bkSzKY/foo/Cargo.lock
  caused by: invalid serialized PackageId for key `package.dependencies`
```

This should just require updating the `cargo` dependency version (or switching to `cargo-metadata` if that provides enough details to get independence from the exact file format, and a reduced build time).

**Comment by CAD97** [comment]
I should note that this issue is preventing me from publishing reviews of [my new crates](https://www.reddit.com/r/rust/comments/f1iixm/); I can't even just use an older toolchain, because they require the trait coherence changes from 1.41.

**Comment by Nemo157** [comment]
As a workaround for now you can use `cargo-lock` to translate back and forth between the formats.

**Comment by dpc** [comment]
Anyone can try to bump the `cargo` dependency and submit a PR?
