### ISSUE TITLE
Goto instructions should show full commands

### ISSUE THREAD

**Issue by Nemo157** [crev-dev/cargo-crev#289]
It's been a while since I used crev, so when I ran `cargo crev goto ...` and saw

```
Use `review` and `flag` without any arguments to review this crate.
```

I assumed this meant that it had installed top-level `review` and `flag` functions into my shell (like `virtualenv` injects a `deactivate` function). It would be good to have this show the full commands you have to run.

```
Use `cargo crev crate review` and `cargo crev crate flag` without any arguments to review this crate.
```

(though `cargo crev crate flag` doesn't appear to exist?)

**Comment by dpc** [comment]
Yeah. This message is stale. Please fill a PR if you can, otherwise I'll do it as some point.
