### ISSUE TITLE
API request: Enumerate all signature/proof pairs in a ProofDB

### ISSUE THREAD

**Issue by niklasf** [crev-dev/cargo-crev#292]
`db.get_pkg_reviews_for_source("https://crates.io")` is close, but there seems to be no way to get the signature.

Loosely related to #137.

**Comment by dpc** [comment]
@niklasf This should be easy enough to add. Just fill a PR, and I'll be happy to land. :)

**Comment by niklasf** [comment]
My goal was to build something like https://github.com/LucianoBestia/cargo_crev_web (before it existed), so I no longer need this feature.
