### ISSUE TITLE
Trust Crev Id without a URL

### ISSUE THREAD

**Issue by kornelski** [crev-dev/cargo-crev#300]
Currently `crev id trust` wants to know a URL for the Id.

> Error: URL not found for Id yadayada; Fetch proofs with `fetch url <url>` first

This means I can't tell others "I'm X98FCpyv5I7z-xv4u-zMWLsFgb_Y0cG7p5xNFHSjbLA add me to crev!" and requires sharing of URL + Id together. It also nudges users towards sharing just the URL, because an Id can be read from a URL.

If crev could create a trust proof without the `url` field, it would make crev Ids more practical for sharing as *the* identity, rather than a secondary thing with *URL* being the identity. 

Related to #298

**Comment by dpc** [comment]
That is true ... . I guess we could make it an `Option<...>`
