### ISSUE TITLE
Failure crate deprecation

### ISSUE THREAD

**Issue by kornelski** [crev-dev/cargo-crev#326]
The failure crate has been deprecated, and hasn't been a good fit for a library either.

I suggest:

* Moving crev-lib to use an `enum`-based error. `thiserror` can be used for boilerplate.

* Moving cargo-crev to `anyhow`, or keeping `failure`

**Comment by dpc** [comment]
Agreed. I wanted to move to anyhow in the binary, anyway.

**Comment by dpc** [comment]
Seems to me this is mostly done, other than `.compat()` on `crates_io_api` types.
