### ISSUE TITLE
TrustSet should preserve explicit distrust

### ISSUE THREAD

**Issue by kornelski** [crev-dev/cargo-crev#330]
For distrusted users `TrustSet.get_effective_trust_level()` returns `None`. I think that's because `calculate_trust_set` uses distrust to remove users from consideration, not to record all of the trust levels.

I need that distinction, because if someone is actively distrusted, I want to totally ignore all of their reviews. If someone is merely unknown, I want to display to user that there exist more reviews with uncertain trust.

**Comment by dpc** [comment]
That might be the case. Go ahead with changes like that. Some stuff is there purely because I haven't thought about them enough.
