### ISSUE TITLE
"file not written to" is overly careful

### ISSUE THREAD

**Issue by chrysn** [crev-dev/cargo-crev#338]
Commands like `cargo crev crate review` and `cargo crev trust` open an editor and refuse to act if the file has not been saved.

The default values in the templates are often rather good (especially a `crev trust` often needs no adjustment). Some editors do not even offer saving if the file is unmodified. (gedit does, vim's :wq does, vim's ZZ does not).

If the check is still considered adequate, maybe a "The file was not saved. Do you confirm the (review, trust setting) with the default values? (y/n)" would be a better message to ask/show.

Cc @dns2utf8 who mentioned he ran into this as well.

**Comment by dpc** [comment]
Someone reported on riot that not writing should cancel, and I think that's how `git commit` works as well. I changed the behavior in https://github.com/crev-dev/cargo-crev/commit/e2c58485c82054d2fec9ea8b3145e01dd9148a3b .

More discussion needed to figure out behavior that is fine with everyone.

**Comment by chrysn** [comment]
`git commit` aborts on an empty message; not writing is fine, and is a typical thing when running `git merge` or `git commit --amend`. Only typical `git commit`, the default message just happens to be empty.

**Comment by dpc** [comment]
We still want some reasonable way out for people that just want to cancel. So I guess asking if the user wants to cancel or commit is a best way to go. I personally got used to and enjoyed that easy way to cancel, even though I myself initially implemented it as "no write == defaults".

We could also make it a setting or something.

PRs welcome. :)
