### ISSUE TITLE
pip-crev (crev for the python package manager)

### ISSUE THREAD

**Issue by ffranr** [crev-dev/cargo-crev#342]
I've been thinking of starting a crev extension for the pip python package manager. @dpc Is it ok if I start a repo on crev-dev?

One key difference between cargo and pip is that pip does not require dependency packages to specify versions. See: https://packaging.python.org/discussions/install-requires-vs-requirements/

It's best practice to specify a lower bound package version, but it's not strictly necessary. How then can crev present a summary of dependency review states? Well I think we have a few options:
1. We could check every possible acceptable version of a given dependency based on a list such as this:  https://pypi.org/project/black/#history (pypi is equivalent to crates.io)
2. We could identify the dependency's version from the current environment or virtual environment.
3. We could make the assumption that we should only consider the latest version of the dependency.

We will probably have to utilize different options in different circumstances (running locally or repo badge status).

**Comment by dpc** [comment]
:tada: 

I have created the repo and made you an admin to unblock you. I'm short on time right now, but will try to come back here and share some opinions soon.

**Comment by ffranr** [comment]
Thanks! Looking forward to hearing any thoughts you may have.

**Comment by dpc** [comment]
My Python-fu is meh, especially around the package handling. `crev` was designed with semver versioning in mind.

> 2. We could identify the dependency's version from the current environment or virtual environment.

Seems most reasonable.

**Comment by ffranr** [comment]
It seems as if a future version of python's package manager will generate and manage a lock file: `Pipfile.lock`, see https://github.com/pypa/pipenv . I think `pip-crev` could fit nicely into that future! I'll close this issue for now and continue in the new repo when necessary.

Right now I'm investigating the best method of calling rust code from python.
