### ISSUE TITLE
CI workflow: "Failed scanning for proofs" warning

### ISSUE THREAD

**Issue by chrysn** [crev-dev/cargo-crev#343]
The currently recommended workflow for running `verify` in CI spits out a nasty warning (looks like an error but is actually ignored further on):

```
Failed scanning for proofs: Error iterating local ProofStore at /home/guest/.config/crev/proofs: IO error for operation on /home/guest/.config/crev/proofs: No such file or directory (os error 2)
```

This happens because no own ID has ever been imported, there just was a `repo fetch` on the relevant repositories, and then the verify is run with `--from-id`.

I've tried patching proofs_iter_for_path with something like

```
        .map_err(move |e| {
            // NotFound errors on the directory are silently ignored as would be the directory
            // being empty.
            let as_std: std::io::Error = e.into();
            if as_std.kind() != std::io::ErrorKind::NotFound {
               // what was there before
            } else {
                // somehow make sure it's not actually shown as an error later on
            }
```

but I'm a bit confused by where this is all called from, as silently ignoring the lack of keys is not something to do in general. It'd probably be acceptable here as an empty proofs directory is accepted silently just as well, but I'm not confident to say this is true for all call sites.

(Tested with 0.17 installed using cargo 1.42).

**Comment by dpc** [comment]
We should probably check if the current id is set, and not try to scan the current user repo dir.
