### ISSUE TITLE
Fast fetching

### ISSUE THREAD

**Issue by kornelski** [crev-dev/cargo-crev#350]
Now that I have many sources added, fetching of updates has become slow. There isn't much to fetch, it's just slow to check many repos.

I suggest two improvements:

* If the source is on GitHub, first check with GitHub API whether there have been any changes. This is what Cargo does in its "fast path" index update. An HTTP request is quicker than a no-op `git fetch`.

* Parallelize fetches. They're mostly slow due to network latency, so it won't harm to throw more packets at the network.

**Comment by dpc** [comment]
I was hoping this  going to be eventually necessary. :)
