### ISSUE TITLE
support for more advanced identity (PKCS#11 / keybase.io)

### ISSUE THREAD

**Issue by tiziano88** [crev-dev/cargo-crev#362]
AFAICT, a crev id is stored locally, and although it is sealed with a user-provided passphrase, it essentially needs to be copied around across devices (or I guess a user may generate a crev id per device, and trust them from each other).

I suggest considering the following:

- allow using hardware-based signatures (e.g. yubikey); this should be possible via PKCS #11 (for which there appears to be a [Rust crate](https://crates.io/crates/pkcs11) already, though I have not tried it myself). This has the advantage that the private key of a crev id would be closer to being physically uncloneable, and at the same time can be shared across devices (by plugging the yubikey on the appropriate device)
- rely on existing key distribution systems; for instance, keybase.io already allows distributing a user's identity across devices, and allows for revocation and enrollment of devices, and also can link to other social media for cross-verification

Curious if these have been considered, or if there is interest in having a discussion about it.

**Comment by dpc** [comment]
https://github.com/crev-dev/cargo-crev/issues/58
