### ISSUE TITLE
What is the format to import a review with `cargo crev repo import`

### ISSUE THREAD

**Issue by LucianoBestia** [crev-dev/cargo-crev#363]
Is it possible to import the same text format as written in Vim?
```json
review:
  thoroughness: high
  understanding: high
  rating: strong
comment: "comment"
```

**Comment by dpc** [comment]
This one is called a "draft", and has bunch of stuff missing, which `cargo-crev` fills for the user.

**Comment by dpc** [comment]
I think `import` requires previous signed proofs, and will re-sign them as a current user.

**Comment by LucianoBestia** [comment]
Is it possible to add new functionality to import the "Vim" yaml text?
Or is there another command for that?
What happens after VIM is saved and closed? Is it a function that can be used for import?
