### ISSUE TITLE
review in markdown

### ISSUE THREAD

**Issue by LucianoBestia** [crev-dev/cargo-crev#365]
Is the text in the field "comment" markdown?

**Comment by dpc** [comment]
It isn't. Right now it is just text. I guess recommending it to be markdown wouldn't be a bad idea.

**Comment by kornelski** [comment]
People already use Markdown in their reviews, so it is de-facto Markdown now.

**Comment by LucianoBestia** [comment]
Good. Markdown is backward-compatible to text, so this is a logical step.
@kornelski, what library do you use to convert markdown to html on lib.rs?

**Comment by kornelski** [comment]
https://gitlab.com/crates.rs/render_readme/
