### ISSUE TITLE
Support for minisign identity

### ISSUE THREAD

**Issue by tiziano88** [crev-dev/cargo-crev#366]
Similar to #362 and #58 , but for https://jedisct1.github.io/minisign/ identities. I have actually just discovered and started using minisign myself, and it seems to solve the signing problem quite neatly, so it may make sense to reuse its identity model.

There is also a [minisign Rust crate already available](https://github.com/jedisct1/rust-minisign) (though probably will require a closer review) (or `cargo-crev` could just use spawn out to the `minisign` binary if preferred).

Mostly I just thought I'd create this issue (in addition to the other two already mentioned) so that people can express interest in specific identities separately, which may be helpful for prioritization.

**Comment by kornelski** [comment]
Identity is a bigger problem than just signatures. Cryptography there is the boring part. Crev tries to build a web of trust. 

minisign may technically be great, but I don't see what it would bring to crev in terms of user-visible features.

**Comment by dpc** [comment]
Not actionable right now, it seems.
