### ISSUE TITLE
Pre-release dependencies have to be pinned

### ISSUE THREAD

**Issue by daxpedda** [crev-dev/cargo-crev#368]
Currently compiling the newest available version of `cargo-crev`, 0.17.0, isn't possible because of semver incompatibilities with pre-release crates.

Specifically in this case:
https://github.com/crev-dev/cargo-crev/blob/91f3e86945c7011a3e3335c1e1e182790e373b1e/crev-data/Cargo.toml#L19
Cargo automatically makes this to `ed25519-dalek = "^1.0.0-pre.3"`, but pre-releases aren't semver compatible.
To pin this, this has to be `ed25519-dalek = "=1.0.0-pre.3"`.

I do believe this has happened before.

**Comment by dpc** [comment]
Oh. I didn't know that. Please submit a PR and we can land right away.
