### ISSUE TITLE
[https://web.crev.dev/] Github url of user profiles is wrong

### ISSUE THREAD

**Issue by Lokathor** [crev-dev/cargo-crev#371]
The URL for [Lokathor](https://web.crev.dev/rust-reviews/author/ZCBwWlOeJyU79adJqX9-irGH5wrmuYxUPXeSrFKuayg/) puts the link to `LucianoBestia` as the github link.

**Comment by dpc** [comment]
Ping @LucianoBestia (the author and maintainer of web.crev.dev (git repo: https://github.com/LucianoBestia/cargo_crev_web)

**Comment by LucianoBestia** [comment]
You probably tried just the link on the bottom of the page. There is the version and repo of the cargo_crev_web project. The link to lokathor is on the top of the page.
I should make it more clear that the footer is about the page and not the content.

**Comment by dpc** [comment]
https://web.crev.dev is a separate project. Please use https://github.com/LucianoBestia/cargo_crev_web . Closing since there's nothing actionable for us right now.
