### ISSUE TITLE
Reproducing the cargo-crev binary

### ISSUE THREAD

**Issue by kpcyrd** [crev-dev/cargo-crev#380]
Hey!

Our rebuilder at Arch Linux has flagged the cargo-crev package as unreproducible, meaning "running the build in an identical build environment doesn't result in an identical binary".

The diff between the official package distributed to users and the package our rebuilder has built looks like this: https://reproducible.archlinux.org/api/v0/builds/33309/diffoscope

You can ignore the `NT_GNU_BUILD_ID`, but there seems to be a difference in the .data section too. Do you have any ideas where this might be coming from? Most of the other rust packages reproduce successfully so it could be from cargo-crev or a dependency.

Thanks!

**Comment by dpc** [comment]
No, sorry. I don't think crev code itself do anything that could break it.
