### ISSUE TITLE
Verify crate contents against repository

### ISSUE THREAD

**Issue by Nemo157** [crev-dev/cargo-crev#386]
There are two very helpful steps that `cargo crev` could provide as a starting point to review a crate, probably as separate subcommands that you can use while in the context of `cargo crev goto`:

 1. Show differences between the published crate files and what has been recorded in `.cargo_vcs_info.json` (I'll just refer to this as the _identified commit_ from now).
 2. Verify that the repository contains a tag for the version number pointing to the identified commit.

These would both not indicate anything malicious if they fail, but depending on how they fail the reviewer may be able to draw additional data to add to their review.

My suggestion for implementation:

 1. Check that the `.cargo_vcs_info.json` exists and has an _identified commit_ to use, with a known VCS.
 2. Attempt to checkout the url given as `package.repository` in the metadata into a temporary sandbox (with pre-confirmation as connecting to the server may be a privacy leak).
    a. If checkout fails, allow user to specify the url in case they are able to derive/find a usable URL.
 3. Verify that the repository contains the identified commit
    a. If it does, generate a diff from the published crate files to the repository content at that commit for the user to peruse.
 4. Print all tags (with name, commit, and signature details if signed) that:
    a. Contain the version number as a substring
    b. Reference the identified commit (both directly and looking through a signed tag).

<sub>Inspired by discussion in <https://internals.rust-lang.org/t/making-crates-io-verify-code-against-repository/14075></sub>

**Comment by kornelski** [comment]
Yup. There's also 2a. Materialize symlinks. 2b. Find the crate within a monorepo. Directory structure of the repo does not have to look like the crate tarball.

**Comment by jrmuizel** [comment]
An attempt at investigating this happened here: https://github.com/ericseppanen/crates_io_analyzer

**Comment by dpc** [comment]
It's tricky enough that I'd make it a separate command, maybe with a prompt on `stderr` that it's available.

**Comment by dpc** [comment]
Probably not doable.
