### ISSUE TITLE
Creating an id without a url and then setting a url is not possible

### ISSUE THREAD

**Issue by nbigaouette** [crev-dev/cargo-crev#388]
I have trouble using `cargo-crev` with a private git repo and so I am experimenting with different ways of creating ids.

I found that if you create an id wiout a url (using the `--no-url` flag) and then try to set a url, `cargo-crev` complains that the id was created without a url and will stop:

```sh
❯ cargo crev id new --https-push --no-url
warning: creating CrevID without a URL.
CrevID will be protected by a passphrase.
You can change it later with `cargo crev id passwd`.
There's no way to recover your CrevID if you forget your passphrase.
Enter new passphrase:
Enter new passphrase again:
Your CrevID was created and will be printed below in an encrypted form.
Make sure to back it up on another device, to prevent losing it.
...

❯ cargo crev repo git remote set-url --push origin https://nbigaouette@git.example.com/nbigaouette/crev-proofs.git
current Id has been created without a git URL
```

The git command fails because it "validates" that a url is set:
https://github.com/crev-dev/cargo-crev/blob/v0.19.1/crev-lib/src/local.rs#L1025-L1031

So there is a chicken and egg problem here...

Also, if I execute the git command manually inside `cargo crev repo dir`, I get `fatal: No such remote 'origin'`.

**Comment by dpc** [comment]
I think `--no-url` is a new feature and @kornelski might be able to help with it better.

As a workaround, I would try to create a repository first (empty commit will do) and use that with a read only https:// url.

**Comment by kornelski** [comment]
CrevID can't function without an HTTP URL configured. That's non-negotiable. All workarounds only delay the inevitable.

`--no-url` makes an incomplete, temporary CrevID that can't be used to publish anything. It will force you to add the URL later.

Please note the difference:

```bash
cargo crev id set-url
```

says where other people will find you. It's your *public* world-wide identity that will be stamped on everything you do in Crev. Don't put any passwords in there.

```bash
cargo crev repo git remote set-url
```

configures how git uploads to the URL you've set in `cargo crev id set-url`.

**Comment by dpc** [comment]
Please re-open if there's anything actionable. I'm doing some cleanup and closing old issues.
