### ISSUE TITLE
Result of mutually-distrusting Ids depends on order they're processed

### ISSUE THREAD

**Issue by kornelski** [crev-dev/cargo-crev#389]
If user A distrusts user B, and user B distrusts user A, it's indeterminate what result this will have on the WoT:

* if A is processed first, then B is excluded, and A isn't distrusted.
* if B is processed first, then A is excluded, and B isn't distrusted.

**Comment by dpc** [comment]
The graph flooding algo that is currently used is processing things according to trust level and distance. So whoever is more trusted will cancel less trusted proofs first. 

There's even a test, IIRC https://github.com/crev-dev/cargo-crev/blob/291abd6d5520547af9a644a62db94c9915131433/crev-lib/src/tests.rs#L282

**Comment by dpc** [comment]
The exact order is determined by https://github.com/crev-dev/cargo-crev/blob/a1ba22d0cc3fdf23d90f5f1331d28465d8bef4f0/crev-wot/src/lib.rs#L1052 . The last one is `Id` which at least makes it deterministic.

**Comment by dpc** [comment]
> The graph flooding algo that is currently used is processing things according to trust level and distance. So whoever is more trusted will cancel less trusted proofs first.

Actually this is not the case. Two IDs at the same effective trust level, distrusting each other will remove both from the trust set. https://github.com/crev-dev/cargo-crev/blob/291abd6d5520547af9a644a62db94c9915131433/crev-lib/src/tests.rs#L324

Kind of a Mutually Assured Destruction.

**Comment by dpc** [comment]
Closing, as I still think that's how I want it to be, and some improvements around handling it will be done for #390
