### ISSUE TITLE
Prettify `cargo crev verify`

### ISSUE THREAD

**Issue by dpc** [crev-dev/cargo-crev#39]
I've improved formatting, but at least some color would help.

**Comment by rffrancon** [comment]
I think the result rows should be sorted: `unknown`, `verified`, and then `flagged`. In this way the most important results will be the most visible. I also think that they should be sorted a second time alphabetically. The summary statistics should then be underneath all of that.

@dpc @Dylan-DPC What do you guys think?

**Comment by dpc** [comment]
I for one like the way stuff is displayed currently. It is easily grepable and shows up in real-time, without having to wait. But I guess the default could be something more human-friendly.

@rffrancon Seems to me that the logical sorting order should be ether `verified, unknown, flagged` or in reverse. Probably flaggged stuff should be at the bottom.  I agree about sorting in alphabetical order.

A `--no-sort` would by nice too that would just display stuff as it goes through it.

**Comment by rffrancon** [comment]
I agree with you. I like the realtime side of it also. But it would just be nice if the results were displayed in a consistent way, changes would be easier to spot. `--no-sort` is a nice plan.

We could also verify asynchronously from what I can tell, but perhaps that is over complicated for this stage.

**Comment by dpc** [comment]
@rffrancon Yeah, the simpler the better.

**Comment by dpc** [comment]
Note: Now `verify deps` will have review counters. 286d69d4ed2d46633275c732d1d9fe60696c4bad

**Comment by hirschenberger** [comment]
I used `verify deps` just now and asked myself what these numbers are. A table header would be great to show what the columns mean.

**Comment by pimotte** [comment]
> I used `verify deps` just now and asked myself what these numbers are. A table header would be great to show what the columns mean.

The header is there now. As a first-time user I could make sense of most of them. flgs stands for flags, and mostly marks crates that have a FFI? The only column I can't grasp is "own." What does that mean?

```
verifi.  reviews     downloads    own. flgs crate               version        
unknown   0  0    94496    243751 0/1       miniz_oxide          0.2.0                                                                                                                                                           
unknown   0  0     1426      1504 0/1       default              0.1.2          
unknown   0  0   417415   1792454 2/6       unicode-segmentation 1.2.1          
unknown   0  0   182481   1894095 1/1  CB   miniz-sys            0.1.11         
unknown   0  0    12135     52632 0/1       darling_macro        0.8.0          
unknown   0  0   952114   3394285 1/1       clap                 2.32.0         
unknown   0  0   595096   2434709 1/1  CB   backtrace-sys        0.1.24 
```

**Comment by dpc** [comment]
@pimotte I'm having a hard time to balance lack of space and staying informative. :)

`CB` is one flag for *Custom Build* . I would like to have more flags like that in the future: `unsafe`, etc. There's an open issue for it. `own.` is *owners* . *known owners* / *total owners*. You can edit *known* owners with `cargo crev edit known`.

**Comment by nbigaouette** [comment]
How about outputing to csv format?

* We could use (as a user) `xsv` to prettify as a table
* The csv would contain the header. If I pipe the versify output to a file (`cargo crev crate verify --show-all --for-id ... > crev.log`) the header is not included in the file.
* Headers are hard to associate to columns due to alignments. Using csv format woulf fix that.

**Comment by dpc** [comment]
@nbigaouette It shouldn't be difficult to add outputs in any format (considering how nice `serde` is). PRs welcome. I really can't invest much time in nice-to-have features right now.

**Comment by dpc** [comment]
Good enough now, methinks.
