### ISSUE TITLE
Changelog entries for 0.19.0 and 0.19.1 are missing

### ISSUE THREAD

**Issue by jcgruenhage** [crev-dev/cargo-crev#392]

**Comment by dpc** [comment]
I'm afraid that we don't have resources to maintain a detailed changelog in face of lots of small changes and releases. :/

**Comment by jcgruenhage** [comment]
Is at least a rough changelog a possibility? If not, I think it'd make sense to remove the changelog, to make the state of no up to date changelog more clear. The old changelog wouldn't be gone either, it's still in the git history after all.

**Comment by dpc** [comment]
There is a rough CHANGELOG and I updated it with some main changes that I've noticed.
