### ISSUE TITLE
Deduced push URL for git.sr.ht is wrong

### ISSUE THREAD

**Issue by robinkrahl** [crev-dev/cargo-crev#395]
I’m currently in the process of setting up crev using a proof repository hosted on [git.sr.ht](https://git.sr.ht).  The `id new` command deduced ([util::git::https_to_git_url](https://github.com/crev-dev/cargo-crev/blob/c610f43e146d7f384de558312d0c59cb3190585a/crev-lib/src/util/git.rs#L85)) the push URL

```
git@git.sr.ht:~ireas/crev-proofs.git
```

for my repository URL

```
https://git.sr.ht/~ireas/crev-proofs
```

Yet on sr.ht, the push URL does not include a `.git` suffix.  In fact, the deduced push URL points to a different repository called `crev-proofs.git`.  (I also considered using my self-hosted Git server.  In this case, the user name would have been wrong too.)

When calling the `publish` command, I first got an error message about uncommitted changes (not sure if some command failed due to the wrong URL or if this is a different issue):

```
$ cargo crev publish
error: cannot pull with rebase: Your index contains uncommitted changes.
error: please commit or stash them.
```

After manually committing the changes, I got an error message due to the missing repository:

```
$ cargo crev publish
Repository not found.

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I managed to fix this by manually editing the repository configuration.  Yet this was very confusing, especially because neither the UI nor the documentation mention this behavior.

I think there should be a `--push-url` option for `id new`.  Also, I suggest to only deduce the push URL for a list of known sites (and fail for others).  If you want to keep deducing the URL for all hosters, it would be useful to at least print a message for unknown sites so that the user has a chance to spot the error.

I can prepare a PR that implements one of these solutions if you agree.

**Comment by dpc** [comment]
Sound good to me. @kornelski any comments?

**Comment by kornelski** [comment]
Yes, `--push-url` would make sense. You could also make push-url-guessing logic aware of this particular host (sadly, there's no URL standard for this, so exceptions for host by host are expected)

**Comment by dpc** [comment]
I've added a list of hosts for which we know how to deduce. Rest of the code will already print a helpful message how to fix it after the fact, which IMO is better than `--push-url` since the user usually will not know that such `--push-url` argument is required.
