### ISSUE TITLE
Allow disabling "vendored" feature for openssl-sys

### ISSUE THREAD

**Issue by kpcyrd** [crev-dev/cargo-crev#400]
I've noticed cargo-crev pulls in `openssl-src`, which means it won't link to the system openssl and needs to do security updates on its own in case of an openssl security update.

Right now it's a hard dependency, it'd be neat if this would be a feature that I can disable (having the feature on by default is fine).

Possibly related to #372

**Comment by dpc** [comment]
:+1: Do you mind pushing a PR through?
