### ISSUE TITLE
Status of TUI?

### ISSUE THREAD

**Issue by kornelski** [crev-dev/cargo-crev#403]
Currently cargo-crev has a bit of an interactive UI implemented, but the progress on it has stalled, and it's now using very outdated deps (`crossterm` and `termimad`).

Is anyone using it? Anyone interested in keeping it alive?

If nobody objects, I'd prefer to remove that code.

**Comment by Minoru** [comment]
This is the first time I hear that cargo-crev has a TUI. The CLI is quite complex and reminds me of GnuPG, but I don't see how a TUI could improve that, so I'd personally be okay with removing the TUI.

**Comment by dpc** [comment]
:+1: remove. If anyone is interested they can find it in git history and make a separate binary or something.
