### ISSUE TITLE
List relevant reviewers that I don't trust yet

### ISSUE THREAD

**Issue by Minoru** [crev-dev/cargo-crev#404]
`cargo crev crate mvp --trust none` lets me list reviewers that are relevant to current crate, i.e. reviewed some of this crate's dependencies. This is a great tool to discover new reviewers from whose work I could benefit. To help this use-case, cargo-crev should omit people whom I already trust. For example, if cargo-crev had a `--max-trust` option, I could set the maximum trust level to `none` and get a list of MVPs whom I don't yet trust:

```
$ cargo crev crate mvp --max-trust none
```

I could further refine the report by excluding people whom I explicitly distrust:

```
$ cargo crev crate mvp --max-trust none --trust none
```

Option name is subject to bikeshedding of course. I'd go with `--min-trust` and `--max-trust`, but that'd be a breaking change (renaming `--trust` to `--min-trust`); I don't know if Crev has policy regarding such changes.

Looking forward to hear your thoughts on this.

**Comment by dpc** [comment]
I like the goal, I'm not sure about how to achieve it in a best way. `crate mvp` is kind of a little know thing that I hacked together for fun without much thinking. I'm looking at how output of `cargo crev id query all` looks like, and it seems to me that would be nice if `crate mvp` had same format + count of review.Which means we would print the `trust` and the id verification symbol. Then user could trivially `| grep none`.  Maybe we should even move `carte mvp` to `id` command line group. 

`--max-trust` etc. seems a bit of additional complexity that we might want to avoid. Donno. No strong opinions.

If you'd like to take a stub at it, I'd be happy to review and land such a feature.

**Comment by dpc** [comment]
Just for reference, even now it's possible to achieve it with:

```
for id in `cargo crev crate mvp --trust none | awk '{ print $2 }'` ; do cargo crev id query all | grep -- "$id" | grep none ; done
```

Maybe it could be its own command?

There's potentially a lot of queries that the user might want to build. We might want to have something like `cargo` where `crev x` would call `crev-x` and `crev-x` would be a standalone binary that was built with `crev-lib` underneath.

**Comment by Minoru** [comment]
As a programmer, I definitely see the appeal of building an extensible interface, but as a user, I just want to know whose reviews I could benefit from :) Your `| grep none` idea sounds great, much better than `--max-trust`.

I'm not sure when I'll get around to this, but I've put this issue on my list. Perhaps I'll work on it the next time I'm annoyed with the MVP report :)

Regarding `crev-x`, I think this is a good way to reduce complexity. Current UI is quite large and, in my opinion, is geared towards scripts not humans. It could be simplified and reduced, and `crev-x` could then provide an escape hatch for those who want more powerful queries (I presume they'll build upon crev-lib instead of using the CLI).

**Comment by dpc** [comment]
The CLI UI is a source of a lot of discussions and went though a lot of changes. In a way, the whole tool was modeled after `git`, and suffers though a lot of similar problems. There's a lot of surface area and functionality available, and it's hard to package it in a way that satisfies everyone, and it introduces new concepts that confuse newcomers. Too many/few categories, some stuff doesn't fit neatly in one category only, too many commands, too many flags, and people have a lot of ideas and use-cases.

Anyway - main developer (kornelski) is very busy and mostly focused on functionality he needs (AFAIU, at least), and I'm the original author, who can no longer dedicate too much time to developer the tool further (at least at the moment). PRs are very appreciated, and the code should by modular enough that changes like this shouldn't take too long to implement and then test locally for a while.
