### ISSUE TITLE
miscreant is dead

### ISSUE THREAD

**Issue by kornelski** [crev-dev/cargo-crev#410]
miscreant crate is no longer maintained, and outdated version of `aes` it uses has been yanked, so as of right now **it's not possible to install cargo-crev any more**.

**Comment by dpc** [comment]
:S

**Comment by dpc** [comment]
> The Rust successor is the aes-siv crate, which is the evolution of the original Miscreant codebase.

https://github.com/miscreant/miscreant.rs

So we just need migrate?

**Comment by kornelski** [comment]
Yup
