### ISSUE TITLE
Path too long on Windows 11

### ISSUE THREAD

**Issue by thargy** [crev-dev/cargo-crev#416]
Fresh install of cargo crev ([was not easy](https://github.com/crev-dev/cargo-crev/issues/372#issuecomment-901958412)).

Following [Getting started guide](/crev-dev/cargo-crev/blob/master/cargo-crev/src/doc/getting_started.md).

```bash
$ cargo crev repo fetch url https://github.com/dpc/crev-proofs
Fetching https://github.com/dpc/crev-proofs... 
path too long: 'C:/Users/tharg/AppData/Local/crev/cache/remotes/github_com_dpc_crev-proofs-zyAEeMRLjv__eDHGtrnPUA/C:/Users/tharg/AppData/Local/crev/cache/remotes/github_com_dpc_crev-proofs-zyAEeMRLjv__eDHGtrnPUA/FYlr8YoYGVvDwHQxqEIs89reKKDy-oWisoO0qXXEfHE/reviews/2018-12-packages-Ua7DxQ.proof.crev'; class=Filesystem (30)
```

As you can see, this is falling into the usual path limit problem on windows (260 characters limit, above path is 282 characters long), along with the inability to install easily on windows, the architecture clearly depends on long paths and so it doesn't seem like this has been tested on Windows at all. 😑 

This is using the latest binary release `0.20.0`.

This looks like a promising project, but I'm going to have to give it a pass until its more stable, and works on Windows (I can't afford a mac 😆, though I guess I could run WSL).

**Comment by thargy** [comment]
Note, I do have `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled (Type: REG_DWORD)` set to `1` on my development environment, so this must be using one of the older APIs which doesn't support long paths.

**Comment by dpc** [comment]
Can you please re-run and let me know what https://github.com/crev-dev/cargo-crev/commit/f57506d950127ae7a55a91676b92d11ab30907c4#diff-8462db02cb2110162f5eeda05cfa36488eade76b6f535f26567920cb4f877e70R64 prints? (`env RUST_LOG=debug` should do)

**Comment by alpha-tango-kilo** [comment]
Sorry it took so long for me to get to testing this, `openssl` was being a right pain with Perl on Windows to build from source

Anyway, I don't get an error now at all, which is awesome! All seems to work swimmingly

**Comment by dpc** [comment]
No worries & thanks! No idea why this was happening and what fixed it. Please reopen if you ever spot it.
