### ISSUE TITLE
Trying to write new crev reviews using crev-lib and crev-data

### ISSUE THREAD

**Issue by LucianoBestia** [crev-dev/cargo-crev#418]
I am working on a GUI for writing crev reviews (CLI + browser).
I would like to use `crev-lib` and `crev-data` to create new review packages proofs.
What are the `digest` and `revision` fields?
How can I calculate them?
I am stuck now with them and I don't know what to do.
I prepared a simple project to show my approach. 
I appreciate any help, thanks :-)

https://github.com/LucianoBestia/cargo_crev_review_new/blob/main/src/bin/cargo_crev_review_new.rs

**Comment by LucianoBestia** [comment]
I am interested to review only `crates.io` packages.  
The crate I want to review must exist inside my local cargo registry cache. It means I really use it in some of my projects.
In `~\.cargo\registry\index\github.com-1ecc6299db9ec823\cache\re\ad\reader_for_microxml` I found this information for a crate:
```
bc688d353fc7c7a2f3f1f5fed9a27fc1773fc710
1.0.0 {
    "name": "reader_for_microxml",
    "vers": "1.0.0",
    "deps": [],
    "cksum": "623616f68a6441e2f61aa01c9bbcf76f4c9989328e0e10ab747e936718791912",
    "features": {},
    "yanked": true,
    "links": null
}
1.1.11 {
    "name": "reader_for_microxml",
    "vers": "1.1.11",
    "deps": [],
    "cksum": "fd50abb1f0d11a59ebe6d3f31446e4af8d0f8a7df668034b6c9b94453fa30c42",
    "features": {},
    "yanked": true,
    "links": null
}...
```
Is the `cksum` field the same as `digest` for crev?

Is the crev `revision` field used only for `git revision`? For `crates.io` packages it can be empty?

**Comment by LucianoBestia** [comment]
I analyzed reviews for the same crate+version from different people. They have all the same digest and revision.
I think `crev` calculates this for the local directory in `cargo registry`, example: `~/.cargo/registry/src/github.com-1ecc6299db9ec823/reader_for_microxml-1.1.11/`.
Can this function be made available in `crev-lib` ?

**Comment by LucianoBestia** [comment]
I succeeded to get `digest` and `revision` fields. Yabba-Dabba-Doo!
Now I have the problem how to get the `crate_root path`.
I commited the change to: 
<https://github.com/LucianoBestia/cargo_crev_review_new/blob/main/src/bin/cargo_crev_review_new.rs>

Is there a plan to make this functions available through crev-lib ?
I had to copy some code from cargo-crev to make it work. May be superfluous, I don't know.

**Comment by LucianoBestia** [comment]
I solved the problem.
Now it works. It is not an elegant solution, but enough for now for my mini project.
If you know a better way to do it, please make me know.
Thanks.

https://github.com/LucianoBestia/cargo_crev_review_new

**Comment by dpc** [comment]
Sorry for not being more helpful, and I'm glad to see you figure it all out. I'm swamped with other work. I can maybe accept PRs to `crev-lib` and `crev-data` for stuff you think are general purpose and you'd like to see it.
