### ISSUE TITLE
`cargo crev verify --show-all` yields different results when called though node's `spawn`

### ISSUE THREAD

**Issue by p-avital** [crev-dev/cargo-crev#428]
Hello,

I'm working on a VSCode extension which would lint `Cargo.toml` files using `cargo audit` and `cargo crev`, to make these tools more user-friendly and hopefully more popular.

To do so, I'm using `child_process.spawn` to run `cargo crev verify --show-all`, but a lot of fields don't show up compared to calling the same command from a terminal.

Are there some environment variables that affect the output of `crev verify` that would justify this behaviour ?

**Comment by dpc** [comment]
@p-avital There's some level of auto-detection there, and flags to control result columns.

BTW. It would probably be useful to add some `--json-output` to make parsing output more robust.

**Comment by dpc** [comment]
https://github.com/crev-dev/cargo-crev/blob/f54289128ad8075ebffe47fd080fdac084f51c2e/cargo-crev/src/deps.rs#L317 either write a new version, or sprinkle with conditionals replacing prints to stdio with collecting to a `Vec<_>` and serializing at the end as json to output.

**Comment by dpc** [comment]
More code pointers to double check your exact issue: https://github.com/crev-dev/cargo-crev/blob/c17fb847d0430d9e286837f07aab456956f33c96/cargo-crev/src/deps/print_term.rs#L18 https://github.com/crev-dev/cargo-crev/blob/a14cd09ee1e3d5e35ef2175d4851052b716342f9/cargo-crev/src/opts.rs#L216

**Comment by p-avital** [comment]
I'd love to have a JSON output, the lack of robustness was already a concern but I wanted a quick prototype before looking into using crev as a lib. Adding a JSON output is probably the most convenient.

I'll look into doing it, but if you feel up to it, it'll probably take you much less time than it would take me :p

Thanks for the quick reply :)

**Comment by dpc** [comment]
Closed and opened #445
