### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by LucianoBestia** [crev-dev/cargo-crev#430]
The cargo-crev logo is not definitively confirmed.
I propose something less graphical and more rusty:
![image](https://user-images.githubusercontent.com/31509965/144755777-4010dac4-e109-4ce3-8b9a-3fbf07a57fff.png)

**Comment by dpc** [comment]
crev is supposed to be language agnostic (even though the only implementation in existence is focused on cargo) :shrug: 

I don't want to play with logos right now. Whatever energy I have for this project, should be put into pressing issues. Once the project gains any traction and more active devs or something, they can figure out the logo the want.
