### ISSUE TITLE
Proofs belong in the data directory, not the config directory

### ISSUE THREAD

**Issue by chris-morgan** [crev-dev/cargo-crev#435]
Proofs are currently placed in the config directory (e.g. ~/.config/crev/proofs). This is wrong: they’re data, not configuration, and so should be in the data directory (e.g. ~/.local/share/crev/proofs). This needs `directories::ProjectDirs::data_dir`, and some shuffling of code as regards the overrides because of the “crev root dir” concept, so that it would probably be reckoned a breaking change. If you’ll accept it, I’m happy to contribute a patch to move it to data_dir.

**Comment by dpc** [comment]
Oh, I guess you're right. I think I'm :+1: 

As for breaking change - somewhere at the start we can detect the directory in the old place, and automatically move it to new.

**Comment by chris-morgan** [comment]
When I said “breaking change” I was thinking of CARGO_CREV_ROOT_DIR_OVERRIDE, but I misunderstood what it did and also conflated it with the CARGO_CREV_GOTO_\* names. I definitely had in mind moving the directory from the old path to the new automatically. So yeah, no breaking change, unless you count the fact that downgrading will require manual action.

I mulled over the matter of identities just now; they could go in either, frankly, but I think config is probably just narrowly more apt for them, so I’ll leave it at just proofs for now. Patch at #442.
