### ISSUE TITLE
check_package_clean_state() move to crev-lib

### ISSUE THREAD

**Issue by LucianoBestia** [crev-dev/cargo-crev#458]
In my project https://github.com/LucianoBestia/cargo_crev_reviews_workspace
I create crev reviews (proof with only ratings and comment) in a GUI full-stack Rust application.
In Cargo.toml l have:
crev-lib="0.22.2"
crev-data="0.22.2"
But we discovered recently, that some of my `digest` data is not correctly calculated.
You precisely found out, that I need to use `check_package_clean_state()`.
 >"For Rust we need to do bunch of shenanigans before calculating digest. See comments."  
https://github.com/crev-dev/cargo-crev/issues/434

But this function is not in `crev-lib`. It is in `cargo-crev/src/shared.rs`. 
Is it possible to move this function to crev-lib?

**Comment by LucianoBestia** [comment]
I recreated the function in my code. No need to move it for me.

**Comment by dpc** [comment]
Just a note:

`crev-lib` is supposed to be language independent functionality only. If anything, we could have `crev-rust` for Rust-specific functionality that is more general than just `cargo-crev` implementation detail.
