### ISSUE TITLE
"Could not find requested crate" even for a direct dependency

### ISSUE THREAD

**Issue by Minoru** [crev-dev/cargo-crev#485]
```
$ cargo new reproducer
     Created binary (application) `reproducer` package
$ cd reproducer
$ cargo add fastrand@1.8.0
    Updating crates.io index
      Adding fastrand v1.8.0 to dependencies.
$ cargo crev crate diff fastrand -- -ruN
    Updating crates.io index
Could not find requested crate. Try `-u` if the crate is not a dependency.
```

The expected output is a diff between fastrand 1.7.0 and 1.8.0 (because 1.7.0 is the latest reviewed version at the moment).

I bisected this to commit 68656a39938cc280e99580ff063b7af93d08c7cd which added `-u`.

* Please let us know:
    * Which version are you using: cargo-crev 0.23.2
    * How did you install `crev`: via `cargo install`
    * What OS/platform are you running on: Debian 11.4

**Comment by dpc** [comment]
Hmm... it works here with 0.23.1 ...

**Comment by dpc** [comment]
Interesting. A workaround is to:

```
cargo crev crate diff -u fastrand -- -ruN
```

but I'll need to look into why non-unrelated codepaths can't look it up.

**Comment by Minoru** [comment]
Yup, adding -u works.

I was hoping you'll spot the problem immediately, but since you can't even reproduce it, I'll find time this weekend to step through it with a debugger and see what's going on.

**Comment by dpc** [comment]
I think this should be already fixed.

**Comment by Minoru** [comment]
Sorry, it's GitHub acting up. I commented via email on 26th of July, but it took GitHub 1.5 months to display the comment ._.
