### ISSUE TITLE
Website's TLS certificate has expired on 2023-03-02

### ISSUE THREAD

**Issue by Kijewski** [crev-dev/cargo-crev#574]
Steps to reproduce:

* Access https://web.crev.dev/
* Be greeted by
  > Did Not Connect: Potential Security Issue […]  
  Websites prove their identity via certificates, which are valid for a set time period. The certificate for web.crev.dev expired on 3/2/2023.

**Comment by dpc** [comment]
Thanks letting us know. It's been a while. @bestia-dev are you still maintaining it?

**Comment by bestia-dev** [comment]
I will check what happened. Maybe the bot for LetsEncrypt did not work.

**Comment by bestia-dev** [comment]
Arghhh, the disk was full and nothing worked. I free some space and now the LetsEncrypt certficate is renewed. I will check the other web applications now.
