### ISSUE TITLE
`No such file or directory` when accessing non existent `ids` directory

### ISSUE THREAD

**Issue by nick-mobilecoin** [crev-dev/cargo-crev#598]
On a new install of 0.24.0, if one runs `cargo crev trust ...` it will try to access the `ids` directory before it is created and fail with an IO error.
A new install of 0.23.0 works fine under the same constraints

The error chain:
- [fs::read_dir()](https://github.com/crev-dev/cargo-crev/blob/a3bb27c0a024ce11c8112a886f478fc7062630f1/crev-lib/src/local.rs#L281)
- [get_current_user_public_ids()](https://github.com/crev-dev/cargo-crev/blob/a3bb27c0a024ce11c8112a886f478fc7062630f1/crev-lib/src/local.rs#L1142)
- [load_db()](https://github.com/crev-dev/cargo-crev/blob/a3bb27c0a024ce11c8112a886f478fc7062630f1/cargo-crev/src/main.rs#L513)
- [run_command()](https://github.com/crev-dev/cargo-crev/blob/master/cargo-crev/src/main.rs#L1086)

If you want to report an issue, please go through the following checklist:

* If a command is failing try running it with `RUST_BACKTRACE=1`
  No new information provided
* Paste the exact command and error and/or outputs (along with the backtrace)
  ```console 
  cargo crev trust --level high --no-commit https://github.com/mobilecoinfoundation/crev-proofs
  I/O: No such file or directory (os error 2)

  Caused by:
      No such file or directory (os error 2)
  ```

* Please let us know:
    * Which version are you using (eg. `cargo crev --version`)
      0.24.0
    * How did you install `crev` (git?, cargo?, your distribution?)
      * Installing by downloading the binary
      * Building locally with `cargo run ...` or `cargo build && ./target ...`
    * What OS/platform are you running on
      * Ubuntu 22.04 (github actions)
      * Mac OS (m2)

**Comment by seanpianka** [comment]
I am also having this issue with the exact same behavior chain.

**Comment by carlaKC** [comment]
Also ran into this issue going through the [getting started guide](https://github.com/crev-dev/cargo-crev/blob/master/cargo-crev/src/doc/getting_started.md):
- `cargo install cargo-crev` on MasOs(m1)
- `cargo crev -version` -> 0.24.0
- Any `cargo crev` command fails with `I/O: No such file or directory (os error 2)` error

**Comment by jayvdb** [comment]
Building 0.23 failed for me.

```
$ rustup run stable cargo install cargo-crev --version 0.23.0
...
   Compiling cargo-crev v0.23.0
error[E0063]: missing fields `distrust_distance` and `none_trust_distance` in initializer of `crev_lib::TrustDistanceParams`
   --> /home/jayvdb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-crev-0.23.0/src/opts.rs:168:9
    |
168 |         crev_lib::TrustDistanceParams {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `distrust_distance` and `none_trust_distance`

For more information about this error, try `rustc --explain E0063`.
error: could not compile `cargo-crev` (bin "cargo-crev") due to previous error
error: failed to compile `cargo-crev v0.23.0`, intermediate artifacts can be found at `/tmp/cargo-installAjpJc4`
```
