### ISSUE TITLE
https://web.crev.dev/ down - is this intended?

### ISSUE THREAD

**Issue by lukaselmer** [crev-dev/cargo-crev#746]
I get redirected from https://web.crev.dev/ to https://web.crev.dev/rust-reviews/, which shows

```
502 Bad Gateway
nginx/1.18.0
```

**Comment by dpc** [comment]
@bestia-dev

**Comment by bestia-dev** [comment]
Thank you for reporting that the site was down.

The site https://web.crev.dev/ is now up and running.
